{% set name = "durationpy" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/durationpy-{{ version }}.tar.gz
  sha256: fd3feb0a69a0057d582ef643c355c40d2fa1c942191f914d12203b1a01ac722a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - durationpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/icholy/durationpy
  summary: Module for converting between datetime.timedelta and Go's Duration strings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
