{% set name = "durationpy" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/durationpy-{{ version }}.tar.gz
  sha256: fd3feb0a69a0057d582ef643c355c40d2fa1c942191f914d12203b1a01ac722a

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - durationpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/icholy/durationpy
  description: |
    Module for converting between datetime.timedelta and Go's Duration strings.
  summary: Module for converting between datetime.timedelta and Go's Duration strings.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/icholy/durationpy
  doc_url: https://github.com/icholy/durationpy/blob/master/README.md

extra:
  recipe-maintainers:
    - ocefpaf
